# Generated by Django 5.2 on 2025-04-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="departement",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
